In [2]:
import sys
import os
os.environ['TIMETAGGER_INSTALL_PATH'] = 'C:\Program Files\Swabian Instruments\Time Tagger'
import TimeTagger as tt
tagger = tt.createTimeTagger()
list(tagger.getChannelList(tt.ChannelEdge.StandardRising))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [2]:
import numpy as np 
np.arange(0, 200000+1000,1000)

array([     0,   1000,   2000,   3000,   4000,   5000,   6000,   7000,
         8000,   9000,  10000,  11000,  12000,  13000,  14000,  15000,
        16000,  17000,  18000,  19000,  20000,  21000,  22000,  23000,
        24000,  25000,  26000,  27000,  28000,  29000,  30000,  31000,
        32000,  33000,  34000,  35000,  36000,  37000,  38000,  39000,
        40000,  41000,  42000,  43000,  44000,  45000,  46000,  47000,
        48000,  49000,  50000,  51000,  52000,  53000,  54000,  55000,
        56000,  57000,  58000,  59000,  60000,  61000,  62000,  63000,
        64000,  65000,  66000,  67000,  68000,  69000,  70000,  71000,
        72000,  73000,  74000,  75000,  76000,  77000,  78000,  79000,
        80000,  81000,  82000,  83000,  84000,  85000,  86000,  87000,
        88000,  89000,  90000,  91000,  92000,  93000,  94000,  95000,
        96000,  97000,  98000,  99000, 100000, 101000, 102000, 103000,
       104000, 105000, 106000, 107000, 108000, 109000, 110000, 111000,
      

In [3]:
1000/2

500.0

In [2]:
import numpy as np 
time_index = np.arange(0,100)*10
time_index

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [2]:
1001 // 1000

1

In [10]:
# print(ch_aom, ch_switch, ch_daq, ch_mw_source)
mw_start = 4000
mw_gate = 500
laser_start = 2000
laser_gate = 15000
daq_high = 100 # in ns
daq_gate = 500
daq_step = 10
n_sample = int((laser_gate + 2*laser_start - daq_high - daq_gate)/10 + 1)
#define digital levels
HIGH=1
LOW=0

seq_daq = []
seq_aom=[(laser_start,LOW),(laser_gate,HIGH),(laser_start,LOW)]*n_sample
seq_switch=[(mw_start,LOW),(mw_gate,HIGH),(laser_start*2+laser_gate-mw_start-mw_gate,LOW)]*n_sample
for i in range(n_sample):
    seq_daq += [(i*daq_step,LOW),(daq_high,HIGH),(daq_gate-daq_high,LOW),(daq_high),(laser_start*2+laser_gate-i*daq_step-daq_high-daq_gate,LOW)]

1841

In [11]:
import numpy as np 
data_container = []
counts1 = np.array([1,2,3])
counts2 = np.array([4,5,6])
data_container.append(counts1)
data_container.append(counts2)
contrast_data = np.array(data_container)
sum_data = np.sum(contrast_data, axis=0)
print(contrast_data)
sum_data

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [7]:
10//3

3

In [2]:
import numpy as np
a = np.array([])
b = np.array([
    [1,2,3],
    [4,5,6]
])
a = b
print(type(a))

<class 'numpy.ndarray'>


In [1]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
result = np.sum(arr[:,1:3], axis=1)
result

array([ 5, 11])

In [5]:
import numpy as np
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
the_dict ={
            'click_channel': 1,
            'start_channel':2,
            'next_channel':-2,
            'sync_channel':tt.CHANNEL_UNUSED,
        }
def _dict(**the_dict):
    print(click_channel)
_dict(the_dict)

TypeError: _dict() takes 0 positional arguments but 1 was given

In [16]:
class ConfigureChannels():
    def __init__(self):
        super().__init__()
        self._pulser_channels = {
            'ch_aom': 0, # output channel 0
            'ch_switch': 1, # output channel 1
            'ch_daq': 2, # output channel 2
            'ch_sync': 3 # output channel 3
        }
        self._timetagger_channels = {
            'click_channel': 1,
            'start_channel':2,
            'next_channel':-2,
            'sync_channel':tt.CHANNEL_UNUSED,
        }
    @property
    def pulser_channels(self):
        return self._pulser_channels
    @property
    def timetagger_channels(self):
        return self._timetagger_channels  
_configure_channels = ConfigureChannels()
pulser = _configure_channels.pulser_channels
pulser

{'ch_aom': 0, 'ch_switch': 1, 'ch_daq': 2, 'ch_sync': 3}

In [1]:
len(range(1,11))

10

In [2]:
seq = [(1000,1),(100,0),(1000,1),(100,0)]
n_histograms = sum([tup[1] for tup in seq])
n_histograms

2

In [ ]:
plot = pg.PlotWidget(enableAutoRange=True)
graph_widget_layout = QVBoxLayout()
graph_widget_layout.addWidget(plot)
frame.setLayout(graph_widget_layout)
plot.setLabel("left","Intensity (Counts)")
plot.setLabel("bottom","Time Bins (ns)")
plot.setTitle('TCSPC Data', color='k')
plot.setBackground(background=None)
plot.getAxis('left').setPen('k')
plot.getAxis('left').setTextPen('k')
plot.getAxis('bottom').setPen('k')
plot.getAxis('bottom').setTextPen('k')
plot.getAxis('top').setPen('k')
plot.getAxis('right').setPen('k')
plot.showAxes(True)
plot.showGrid(x=True, y=True)

In [13]:
import numpy as np
a = []
b = np.array([
    [1,2,3],
    [4,5,6]
])
c = np.array([
    [7,8,9],
    [10,11,12]
])
a.append(b)
a.append(c)
d = sum(a)
c = np.sum
c(d,axis=0)
d[1]

array([14, 16, 18])

In [12]:
class myclass:
    def __init__(self):
        print(hasattr(self, '_tcspc_index'))
        self.create_attr()
        print(hasattr(self, '_tcspc_index'))
    def create_attr(self):
        self._tcspc_index = [1,2,3]

myclass = myclass()

False
True


In [7]:
from pulsestreamer import findPulseStreamers, PulseStreamer
devices = findPulseStreamers()
ip = devices[0][0]
pulser = PulseStreamer(ip)

Connect to Pulse Streamer via JSON-RPC.
IP / Hostname: 169.254.8.2
Pulse Streamer 8/2 firmware: v1.7.2
Client software: v1.7.0


In [7]:
start_freq = int(2700*1e6)
stop_freq = int(3000*1e6)
step_freq = int(1*1e6)

freq = range(start_freq,stop_freq+step_freq,step_freq)
for i in freq:
    print(i)

2700000000
2701000000
2702000000
2703000000
2704000000
2705000000
2706000000
2707000000
2708000000
2709000000
2710000000
2711000000
2712000000
2713000000
2714000000
2715000000
2716000000
2717000000
2718000000
2719000000
2720000000
2721000000
2722000000
2723000000
2724000000
2725000000
2726000000
2727000000
2728000000
2729000000
2730000000
2731000000
2732000000
2733000000
2734000000
2735000000
2736000000
2737000000
2738000000
2739000000
2740000000
2741000000
2742000000
2743000000
2744000000
2745000000
2746000000
2747000000
2748000000
2749000000
2750000000
2751000000
2752000000
2753000000
2754000000
2755000000
2756000000
2757000000
2758000000
2759000000
2760000000
2761000000
2762000000
2763000000
2764000000
2765000000
2766000000
2767000000
2768000000
2769000000
2770000000
2771000000
2772000000
2773000000
2774000000
2775000000
2776000000
2777000000
2778000000
2779000000
2780000000
2781000000
2782000000
2783000000
2784000000
2785000000
2786000000
2787000000
2788000000
2789000000
2790000000

In [1]:
import pyvisa
rm = pyvisa.ResourceManager()
ls = rm.list_resources()


('GPIB0::19::INSTR',)

In [4]:
list = [1,2,3,4,5,6,7,8,9,10]
list[0:3]

[1, 2, 3]

In [2]:
float(0.500)

0.5

In [3]:
import numpy as np
np.arange(0,10+0.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [1]:
import numpy as np

# 原始列表
original_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 转换为NumPy数组
numpy_array = np.array(original_list)

# 分割成子数组
subarrays = np.split(numpy_array, [3, 6])

# 按照要求进行组合
result = np.concatenate(subarrays)

# 将结果转换为列表
result_list = result.tolist()
print(subarrays)
print(result_list)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
example_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9],
                          [10, 11, 12],
                          [13, 14, 15],
                          [16, 17, 18],
                          [19, 20, 0]])
# 将每一列的元素相加
sum_per_row = np.sum(example_array, axis=0)

# 输出结果
print(sum_per_row)

[70 77 63]


In [2]:
import numpy as np
np.zeros(10)
# np.ones(10) + np.ones(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
with open('a.lst', 'r', encoding='Windows-1252') as file:
    lines = file.readlines()

for line in lines:
    # 处理每一行的数据，例如打印它们或进行其他操作
    print(line.strip())  # 去除行尾的换行符并打印每一行的内容

1M
ÿÿð?4@ð?ð?i@Y@ð?@@ô½áóç
#ja.lst@Y@i@4@T@À_À€_ÀI@p§@@@@À_À"@"@`ãFA

In [6]:
import pandas as pd
import numpy as np
list = [1,2,3,4,5,6,6,7,7,7,8,8,9,9,9,0,1,0,1,9,2,8,8,7,6]
data = np.array(list)
print(data)
series = pd.Series(data, name='Name')

series.to_csv('test.csv', index=False, header=True)

[1 2 3 4 5 6 6 7 7 7 8 8 9 9 9 0 1 0 1 9 2 8 8 7 6]
